name: Generate a demo project

on: 
  push:
    branches:
      - master
      - next
  schedule:
    - cron: '0 10 * * 3'

jobs:
  generate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Install dependencies
      run: npm i

    - name: Generate project
      run: node_modules/.bin/moleculer init --answers test/ci/answers.full.json --no-install . project-demo

    - name: Initialize Git repo
      run: git init
      working-directory: ./project-demo

    - name: Set remote
      run: git remote add origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/moleculerjs/project-typescript-demo.git
      working-directory: ./project-demo

    - name: Add files
      run: git add --all
      working-directory: ./project-demo

    - name: Configure Git user
      run: git config --global user.email "hello@moleculer.services" && git config --global user.name "Moleculer"
      working-directory: ./project-demo

    - name: Commit
      run: git commit -m "Generated files (${{ github.sha }})"
      working-directory: ./project-demo
    
    - name: Git push
      run: git push --force origin master
      working-directory: ./project-demo
