name: Test with Kubernetes

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        transporter: [NATS, Redis, MQTT, AMQP, AMQP10, STAN, Kafka]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js with ${{ matrix.transporter }} transporter
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm i

    - name: Create answers file
      run: node update-answers.js
      working-directory: ./test/ci
      env:
        TRANSPORTER: ${{ matrix.transporter }}

    - name: Generate project with '${{ matrix.transporter }}' transporter
      run: npm test

    - name: Run tests in the generated project
      run: npm test
      working-directory: ./ci-test

    - name: Start a local Docker Registry
      run: docker run -d --restart=always -p 5000:5000 --name registry registry:2

    - name: Build Docker image
      run: docker build -t ci-test:demo .
      working-directory: ./ci-test

    - uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.17.0"
        config: ./test/ci/kind-config.yaml

    - run: kubectl cluster-info
    - run: kubectl get nodes
    - run: kubectl get pods -n kube-system

    - name: Load Docker image
      run: kind load docker-image ci-test:demo ci-test:demo

    - name: Install NGINX Ingress
      run: kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

    - name: Kubectl apply
      working-directory: ./ci-test
      run: |
        # Fix nginx ingress issue: https://github.com/kubernetes/ingress-nginx/issues/5401#issuecomment-662424306
        kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
        sed 's/image: ci-test/image: ci-test:demo/g' k8s.yaml | kubectl apply -f -

    - name: Sleeping 120 secs
      run: sleep 120

    - name: Check pods
      run: kubectl get all

    - run: curl --silent --show-error --fail http://ci-test.127.0.0.1.nip.io/api/greeter/hello
    - run: curl --silent --show-error --fail http://ci-test.127.0.0.1.nip.io/api/products

    - name: Check logs
      run: kubectl logs deployment/products
